language: python
python:
  - 3.7
  - 3.8

matrix:
  include:
    - python: 3.8
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
        - pip install pylama
      script:
        - pylama tsstats

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest-cov

script: py.test --cov=tsstats tsstats/

after_success:
  - pip install coveralls
  - coveralls
