language: python
python:
  - 2.7
  - 3.5
  - 3.6

matrix:
  include:
    - python: 2.7
      install:
        - pip install -r requirements.txt
        - pip install -r testing_requirements.txt
        - pip install flake8
        - pip install isort
      script:
        - flake8 tsstats/**/*.py
        - isort -c tsstats/**/*.py

install:
  - pip install -r requirements.txt
  - pip install -r testing_requirements.txt
  - pip install pytest-cov

script: py.test --cov=tsstats tsstats/

after_success:
  - pip install coveralls
  - coveralls
