language: python
python:
  - 2.7
  - 3.5

matrix:
  include:
    - python: 2.7
      install:
        - pip install pyflakes
        - pip install isort
      script:
        - pyflakes **/*.py
        - isort -c **/*.py

install:
  - pip install -r requirements.txt
  - pip install -r testing_requirements.txt
  - pip install pytest-cov

script: py.test --cov=tsstats tsstats/

after_success:
  - pip install coveralls
  - coveralls
