language: python
python:
  - 2.7
  - 3.7

matrix:
  include:
    - python: 2.7
      install:
        - pip install -r requirements.txt
        - pip install -r testing_requirements.txt
        - pip install pylama
      script:
        - pylama tsstats

install:
  - pip install -r requirements.txt
  - pip install -r testing_requirements.txt
  - pip install pytest-cov

script: py.test --cov=tsstats tsstats/

after_success:
  - pip install coveralls
  - coveralls
